### ISSUE TITLE
Exclude scenarios for several pages at once

### ISSUE THREAD

**Issue by mattwynne** [cucumber-ltd/bbc-a11y#16]
@joshrp suggested this at yesterday's hack day. The reason is that there will be whole categories of page that should have specific checks disabled.

One idea I have in mind is something like this:

````
BBC::A11y.configure do
  skip_scenario "W3C", for_pages: /list/
end
````

That would add the skip rule for any page whose URL matches the regepx `/list/`.

WDYT @joshrp?

**Comment by joshrp** [comment]
I was thinking keeping similar to the page invocation structure: 

```ruby
configure_page /^(article|section)/[\w]+/ do
    skip_scenario "W3C"
end
```
Kind of on it's head implementation wise but it feels weird having the `skip
_scenario` (and any other methods) manage which pages they run on.
?

**Comment by mattwynne** [comment]
OK, I see. How about if we called it this:

```
for_pages_matching /^(article|section)\/[\w]+/ do
  skip_scenario "W3C"
end
```

**Comment by joshrp** [comment]
Looks good to me!
