### ISSUE TITLE
Clarify Form Labels rule

### ISSUE THREAD

**Issue by mattwynne** [cucumber-ltd/bbc-a11y#28]
In implementing the checks for Form Labels (#27) I [had a question about the title attribute rule](https://github.com/cucumber-ltd/bbc-a11y/pull/27#discussion_r26907320). In the examples under "Fail" we see:

```
<input type="text" name="name" title="Name" />
<input type="text" name="email" title="Email" />
```

Yet these both have a title attribute. I'm wondering why they're supposed to fail? Is the rule that the title attribute is only OK if there's only one field in the form?

**Comment by IanPouncey** [comment]
A title attribute to label a form field is acceptable if there is only one field other than `input[type=hidden,submit,reset,image]`


Pass
```
<form action="#">
    <input type="hidden" name="token" value="qwert1234">
    <input type="text" name="name" title="Name">
    <input type="submit" value="Submit">
</form>
```

Fail
```
<form action="#">
    <input type="hidden" name="token" value="qwert1234">
    <input type="text" name="name" title="Name">
    <input type="text" name="email" title="Email">
    <input type="submit" value="Submit">
</form>
```
