### ISSUE TITLE
Automate form interactions standard

### ISSUE THREAD

**Issue by mattwynne** [cucumber-ltd/bbc-a11y#37]
Split off from #11.

See https://github.com/cucumber-ltd/bbc-a11y/blob/master/standards/19_form-interactions.md

**Comment by mattwynne** [comment]
There's a mix of easy and very-hard in this one, I think.

Checking for a submit button is trivial. Testing the effect of triggering change, focus or blur events might be possible, but sounds tough to do in a fool-proof way.

**Comment by IanPouncey** [comment]
Checking for the submit button is a high value test.

I don't think there is sufficient value to automate testing visible changes that may lead to false positives.

**Comment by joshski** [comment]
We are checking for submit buttons.
