### ISSUE TITLE
Automate min font sizes standard

### ISSUE THREAD

**Issue by mattwynne** [cucumber-ltd/bbc-a11y#39]
Split off from #11.

See https://github.com/cucumber-ltd/bbc-a11y/blob/master/standards/21_min-font-sizes.md

**Comment by mattwynne** [comment]
I think this is possible, with a configuration hook to specify a selector for the core content, defaulting to `<main>`.

**Comment by joshski** [comment]
Min font sizes rule is automated now... can we open a new issue for the <main> bit?

**Comment by joshski** [comment]
I think we should close this, because the font-size standard is automated, and the "core content must be >= 13px" would require a definition of "core content" which is probably too difficult to be worth it.

**Comment by mattwynne** [comment]
I agree. @EmmaJP are you with us?

**Comment by EmmaJP** [comment]
Agreed.
