### ISSUE TITLE
Document the examples

### ISSUE THREAD

**Issue by EmmaJP** [cucumber-ltd/bbc-a11y#41]
It would be helpful to have the examples documented, explaining what they show and how a user could replicate them.

**Comment by joshski** [comment]
We don't mean these examples do we? https://github.com/cucumber-ltd/bbc-a11y/tree/master/examples

Is there anything to do here?

**Comment by mattwynne** [comment]
I think we could remove those examples. I used them very early on when there were no real tests.

**Comment by EmmaJP** [comment]
Those examples provided a way to know how to write the a11y.rb file.  Is there other documentation to help with that?  The detail in 'getting started' is very minimal, though perhaps there is only a few things now.

bbc-pages gave a simple example, while local-web-app had started to look at how a11y could work inside Reith for doing things like HTML validation.

The current example (https://github.com/cucumber-ltd/bbc-a11y/blob/master/a11y.rb) is simple and in keeping with the documentation.  Is it sufficient?

**Comment by mattwynne** [comment]
Really, those examples were created very early on as a way to manually test the first versions of a11y before it had any automated tests. I don't think they made for very good documentation, and we'd be better off looking at some real-world examples and brining them into the README I think.

**Comment by EmmaJP** [comment]
I wasn't suggesting keeping the examples.  Just asking if the current information is sufficient or if there are other commands that are supported if included in the a11y.rb file that are not yet documented.
