### ISSUE TITLE
Summary report when checks completed

### ISSUE THREAD

**Issue by EmmaJP** [cucumber-ltd/bbc-a11y#44]
It would be helpful to have a summary report when all checks have been completed.  What format this should take is open for discussion, but perhaps a simple table mapping pass/fail of tests against pages checked might do for starters.

**Comment by mattwynne** [comment]
http://tenon.io gives really nice results.

**Comment by mattwynne** [comment]
Much improved since 7664d4ee4b5aa2c67c73d816f442bf8bb759c959.
