### ISSUE TITLE
Chrome GUI prototype

### ISSUE THREAD

**Issue by mattwynne** [cucumber-ltd/bbc-a11y#56]
Let's play around with how we can create an interactive UI for a11y running in a browser.

We could use this to:

- run checks on an individual page
- run checks on several pages
- allow you to pull out a JSON config that you can use for your CI build
- diagnose issues by drilling down to individual elements on the page that are causing problems.

It might be a standard chrome plugin-in, or a developer tools plug-in, or a combination of both.

**Comment by joshski** [comment]
Prototype implemented here: https://github.com/cucumber-ltd/bbc-a11y/tree/chrome-extension

**Comment by joshski** [comment]
So I'm closing it... make more issues to describe what we actually want out of the Chrome GUI
