### ISSUE TITLE
Nice output at the end of a test run

### ISSUE THREAD

**Issue by staylos92** [cucumber-ltd/bbc-a11y#67]
It would be nice if there was some brief output at the end of running the tool like:

Number of tests ran: xx 
Passed: xx 
Failed: xx

So that it is clear that a number of tests have been performed. If there are no failures there is currently nothing in the output and therefore it is unclear if everything went well or no tests were actually run.

**Comment by EmmaJP** [comment]
See issue #68 ... also Ignored: xx
