### ISSUE TITLE
Image inserted with JS - Missing alt attribute 

### ISSUE THREAD

**Issue by greenc05** [cucumber-ltd/bbc-a11y#73]
I just found an image in the source code inserted with JS (for stats tracking) on the following page that doesn't have an alt attribute.

I don't get a reported error about this when I run the a11y tool on this page, does the tool run before JS has been executed?

URL: http://www.bbc.com/mundo

```
<img src="http://b.scorecardresearch.com/b?c2=18897612&amp;ns_type=view&amp;ns_site=bbc-global-test&amp;c1=2&amp;ns_alias=61c64bc4-2097-4a50-9412-bf653ae1f7a9&amp;b_imp_src=ws&amp;b_imp_ver=1.0.0.0&amp;b_s_vi=%5BCS%5Dv1%7C2AE5A7F105191882-600006032000EC16%5BCE%5D&amp;name=mundo&amp;b_site_section=homepage&amp;b_page_type=IDX%7Cna&amp;c8=Noticias+-+BBC+Mundo&amp;b_app_type=web&amp;b_app_name=news%7Cweb&amp;b_article_id=9666737&amp;b_article_date=1236879777&amp;b_article_update=1451913574&amp;b_ad_enabled=1&amp;c7=http%3A%2F%2Fwww.bbc.com%2Fmundo&amp;b_c7=%2Fmundo&amp;ns_c=utf-8&amp;ns__t=1451916148&amp;b_vp=1436&amp;b_vph=782&amp;b_sr=1680x1050&amp;bbc_site=news-ws-mundo&amp;b_vs_un=ws&amp;b_vs_ls=mundo&amp;b_synd_partner=bbc%7Crd%7Cgroup4&amp;c9=" class="comscore-tracking-beacon" style="display: none;">
```

**Comment by joshski** [comment]
Thanks @greenc05, perfect timing!

a11y doesn't actually run javascript, so it won't catch issues like this one, unless...

I have reworked a11y so that it mostly runs inside a browser now. That means it will catch this evil pixel because it runs after Javascript and css.

I'll merge these changes soon, just wanted to solicit any feedback first:

https://github.com/cucumber-ltd/bbc-a11y/pull/72

**Comment by greenc05** [comment]
Super, sounds good @joshski Thank you!

**Comment by joshski** [comment]
Hi @greenc05 - I have merged the changes that affect this issue now.

Just gave it another test and it appears this tracking image has an alt attribute with no value:

```
<img src="http://b.scorecardresearch.com/b?c2=18897612&amp;ns_type=view&amp;ns_site=bbc-global-test&amp;c1=2&amp;ns_alias=0700d4f1-0fa2-4f8d-91de-8fe62ad2b8a5&amp;b_imp_src=ws&amp;b_imp_ver=1.0.0.0&amp;name=mundo&amp;b_site_section=homepage&amp;b_page_type=IDX%7Cna&amp;c8=Noticias+-+BBC+Mundo&amp;b_app_type=web&amp;b_app_name=news%7Cweb&amp;b_article_id=9666737&amp;b_article_date=1236879777&amp;b_article_update=1456303867&amp;b_ad_enabled=1&amp;c7=http%3A%2F%2Fwww.bbc.com%2Fmundo&amp;b_c7=%2Fmundo&amp;ns_c=utf-8&amp;ns__t=1456310426&amp;b_vp=596&amp;b_vph=776&amp;b_sr=2560x1440&amp;bbc_site=news-ws-mundo&amp;b_vs_un=ws&amp;b_vs_ls=mundo&amp;b_synd_partner=bbc%7Crd%7Cgroup2&amp;c9=" class="comscore-tracking-beacon" alt="" style="display: none;">
```

We have a scenario that covers this, and our example suggests an empty alt attribute is still valid. I think this means we can close this issue... unless you disagree with the implementation?

**Comment by greenc05** [comment]
Yep an empty alt attribute is totally valid (I added it to the code above), I think my issue before was that before there was no alt attribute and this wasn't caught with the tool, but that was before we ran the tests in a browser, so all is good thanks @joshski

**Comment by joshski** [comment]
Thanks @greenc05, closing...
