### ISSUE TITLE
CSS hiding elements to screen readers being ignored

### ISSUE THREAD

**Issue by greenc05** [cucumber-ltd/bbc-a11y#74]
On the following page: 
http://www.bbc.co.uk/news/video_and_audio/uk 

I get the following error when I run the tool:
A document must have exactly one heading. Found 2 h1 elements.

One of the h1 elements has the following CSS and therefore is hidden to screen readers, leaving just one h1 element available to screen reader users.

display: none;
visibility: hidden;

Will the new DOM reimplementation solve such issues @joshski?

**Comment by joshski** [comment]
It should do yes. We might need to tweak the standard to only consider visible elements...

**Comment by greenc05** [comment]
Super thanks @joshski

**Comment by joshski** [comment]
Fixed in #82
