### ISSUE TITLE
Results Message

### ISSUE THREAD

**Issue by greenc05** [cucumber-ltd/bbc-a11y#77]
Would it be worth while adding a message to the results after the tool has been ran to remind people that just because you may have no errors it doesn't actually mean your page is useable???

Something like 'No errors found. This does not mean you are providing a good experience, you should also perform manual testing using assistive technologies like VoiceOver, JAWS and NVDA.'

**Comment by mattwynne** [comment]
Nice idea! Can we make the copy a bit more friendly / positive?

Suggestion:

```
No errors found. But please remember:

"Testing shows the presence, not the absence of bugs" -- Edsger W. Dijkstra

I am only a robot. Always make time to perform manual testing using assistive technologies like VoiceOver, JAWS and NVDA to make sure you're providing a good experience.
```

**Comment by greenc05** [comment]
Awesome @mattwynne
