### ISSUE TITLE
Better contributor guide

### ISSUE THREAD

**Issue by mattwynne** [cucumber-ltd/bbc-a11y#89]
Ideally explaining how the features work, and how to add new examples when you want to tweak the checks.

**Comment by joshski** [comment]
I think this is covered now, please reopen if anything is missing.

**Comment by EmmaJP** [comment]
Maybe bold the "issues or pull requests" in the first sentence ... just to emphasise that.

**Comment by mattwynne** [comment]
I've made them links @EmmaJP - is that better?

**Comment by EmmaJP** [comment]
Sure :)
