### ISSUE TITLE
Non-input element has title attribute

### ISSUE THREAD

**Issue by greenc05** [cucumber-ltd/bbc-a11y#95]
When running the tool on bbc.co.uk/news I get the following error:

Non-input element has title attribute: /html/head/iframe

This element is an iframe in the head and has display: none applied to it and therefore shouldn't be reported as an error

**Comment by EmmaJP** [comment]
Agreed, that if display is none, this possibly should not be tested.

However, the test is regarding a title attribute and not a display value that requires rendering (like font-size).  The guideline for title attributes requires that they are not used for anything critical (as they may not be seen/spoken) and that they should not repeat something already within the element content.

The rationale advises only to use title on form inputs that do not already have a label.  However, there is nothing explicitly in the guideline prohibiting the use of title attributes on other elements.

@joshski Please could we adjust the tests about title attributes to only test two things.  That the title string does not match something in the contained text.  And that an input element with an associated label does not have a title attribute (this would be the same test used when checking form labels).  The third check mentioned (that the title is not critical content) would be very difficult to automate.  Perhaps later it might trigger an info/warning to manually check any title tags found.

**Comment by joshski** [comment]
Hi @EmmaJP,

> the title string does not match something in the contained text.

I'm not sure exactly what you mean... any chance you could post an HTML example?

> an input element with an associated label does not have a title attribute

Please confirm this new scenario covers it:

```
  Scenario: Field with label AND title attribute
    Given a page with the body:
      """
      <label for="search">Search the BBC</label>
      <input type="text" id="search" name="q" title="Search the Beeb" />
      """
    When I validate the "fields must have labels or titles" standard
    Then it fails with the message:
      """
      Field has label AND title: /html/body/input
      """
```

**Comment by EmmaJP** [comment]
Hi Josh,  

Your scenario above tests the second point I made.  Something like the following should cover the first point:

Scenario: Hidden element with title attribute that does not match content
     Given a page with the body:
       """
       <iframe style="display:none" title="Ignore me, I'm invisible"></iframe>
       """
     When I validate the "title attributes" standard
     Then it passes

Scenario: Visible element with title attribute that does not exactly match all or part of content
     Given a page with the body:
       """
       <span title="This page has been shared 1629 times">1.6K</span>
       """
     When I validate the "title attributes" standard
     Then it passes
 
Scenario: Element with title attribute that exactly matches content
     Given a page with the body:
       """
       <span class="replace-visible-with-icon" title="1.6K">1.6K</span>
       """
     When I validate the "title attributes" standard
     Then it fails with the message:
      """
      Title attribute matches content: /html/body/span
      """
 

Although not great code, this example in the last scenario of the feature file is not really a "title attribute" fail, although it should fail the check for alt attribute on an image:

Scenario: Anchor tag with title attribute
      <a href="close" title="Close Button">
        <img src="close.png" />
      </a>


That does make me think of some other examples that should also fail, involving matching alt text and title text, as alt text could be considered contained text if an image does not load.  Both the following could be considered example, but I'm not sure how much extra complexity they may add:

<a href="close" title="Close Thing"><img alt="Close Thing" src="close.png" /></a>
<a href="close"><img alt="Close Thing"  title="Close Thing" src="close.png" /></a>
