### ISSUE TITLE
Headings - No content follows

### ISSUE THREAD

**Issue by greenc05** [cucumber-ltd/bbc-a11y#98]
@EmmaJP I was just looking at /bbc-a11y/features/check_standards/headings.feature

I'm getting the following error on a h1, is this standard correct or does the test need tweaking?

```
http://bbc.com/vietnamese
  - No content follows: /html/body/div[1]/div[7]/div/div[3]/div[3]/div[2]/div/div[2]/div[3]/h1
```
<img width="571" alt="screen shot 2016-02-03 at 14 05 07" src="https://cloud.githubusercontent.com/assets/1061401/12784462/367958f8-ca7f-11e5-994b-0894c8234f09.png">

```
Scenario: No content between headings
    Given a page with the HTML:
      """
      <div role="main">
        <h1>Main heading</h1>
        <p>non-heading content</p>
        <h2>Secondary content</h2>
        <h2>Tertiary content</h2>
        <p>non-heading content</p>
      </div>
      """
    When I validate the "content must follow headings" standard
    Then it fails with the message:
      """
      No content follows: /html/body/div/h2[1]
      """
```

It is quite likely that a h2 might follow a h1 without any content in between, especially on an index page for example:

```
<h1>Business</h1>
<h2>Top stories</h2>
```

**Comment by IanPouncey** [comment]
Hello Catharine,

It's great to see so much progress made to bbc-a11y recently, I'm looking forward to seeing the finished article.

I happened to see this in my email so I thought I'd comment.

If you are getting an error from that code then it is probably an error in the test. The key bit of the standard is "A heading should always be followed either by non-heading content or by a heading of one level deeper.", and it looks like this is the intent of the tests.

```
Scenario: Headings jump back up more than one level
    Given a page with the HTML:
      """
      <h1>Heading 1</h1>
      <h2>Heading 2</h2>
      <h3>Heading 3</h3>
      <h4>Heading 4</h4>
      <h2>Heading 2b</h2>
      <h3>Heading 3b</h3>
      """
    When I validate the "headings must be in ascending order" standard
    Then it passes
```

is a pass because `<h1>Heading 1</h1>` is followed by `<h2>Heading 2</h2>`, but:

```

  Scenario: No content between headings
    Given a page with the HTML:
      """
      <div role="main">
        <h1>Main heading</h1>
        <p>non-heading content</p>
        <h2>Secondary content</h2>
        <h2>Tertiary content</h2>
        <p>non-heading content</p>
      </div>
      """
    When I validate the "content must follow headings" standard
    Then it fails with the message:
      """
      No content follows: /html/body/div/h2[1]
      """
```

fails because `<h2>Secondary content</h2>` is not followed by content or a heading of one level deeper.

**Comment by EmmaJP** [comment]
Surely the first test example should fail the second test (no content between a h4 and h2).

Nice to see you pitch in Ian.

I agree with what Ian said.  A lower level heading would be considered content.

@joshski could the test please be adjusted to cover this.

<div role="main">
  <h1>Main heading</h1>
    <h2>Secondary content</h2>    <<< lower level heading ok content of h1
    <h2>Secondary content</h2>    <<< same level heading not ok as content
        <p>non-heading content</p>
    <h2>Secondary content</h2>    <<< previous h2 has content, this starts new content block
      <h3>Tertiary content</h3>       <<< lower level heading ok content of h2
        <p>non-heading content</p>
</div>

Hope that helps it make sense.

**Comment by greenc05** [comment]
Thanks @IanPouncey Nice to hear from you, hope all is well 8)

Thanks too @EmmaJP

**Comment by IanPouncey** [comment]
Hi @EmmaJP and @greenc05,

Yes, the structure in `Scenario: Headings jump back up more than one level` would fail `Scenario: Content between headings`, but it passes it's own test, which should allow for heading levels to go back to a lower level, representing that the `<h4>` is the last heading that relates to the `<h3>` and `<h4>` that come before it, and the following `<h2>` is a new part of the document at the same level as the first `<h2>`.

The code you've provided looks like a good test to me, @EmmaJP.
